spring.application.name=mongo-vector-search
#ankit
spring.data.mongodb.uri= 
spring.data.mongodb.database=sample_mflix
spring.ai.x.api-key=x_api_key
ankit.mobile=+91_6200_974_324
x.profile=@ankitkumarpm 
x.email=ankitpm01@gmail.com
x.full.name=ankit_kumar_singh